include:
  - board: seeeduino_xiao_ble
    shield: corne_central_dongle prospector_adapter
  - board: nice_nano_v2 nice_view_adapter nice_view
    shield: corne_central_left
  - board: nice_nano_v2 nice_view_adapter nice_view
    shield: corne_peripheral_left
  - board: nice_nano_v2 nice_view_adapter nice_view
    shield: corne_peripheral_right
  - board: nice_nano_v2 
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
