include:
  - board: seeeduino_xiao_ble
    shield: corne_dongle prospector_adapter
  - board: nice_nano_v2
    shield: corne_central_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: corne_peripheral_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: corne_peripheral_right nice_view_adapter nice_view
# reset settings
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
